name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check project structure
      run: |
        echo "Checking Android project structure..."
        ls -la app/src/main/
        echo "✓ Android source found"
        
        echo "Checking native code..."
        ls -la app/src/main/cpp/
        echo "✓ Native C++ code found"
        
        echo "Checking web viewer..."
        ls -la web/
        echo "✓ Web viewer found"
        
        echo "All checks passed!"
