name: Web Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Check TypeScript files
      working-directory: ./web
      run: |
        echo "Checking web viewer files..."
        ls -la
        echo "✓ Web files found"
        
        if [ -f "package.json" ]; then
          echo "✓ package.json exists"
          npm install
          echo "✓ Dependencies installed"
        fi
