name: Web Viewer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
        
    - name: Install dependencies
      working-directory: ./web
      run: npm ci
      
    - name: Build TypeScript
      working-directory: ./web
      run: npm run build
      
    - name: Upload web artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: web/dist/
